name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Tokens
        working-directory: packages/design-system
        run: pnpm --filter @repo/tokens run build

      - name: Build Design System
        working-directory: packages/design-system
        run: pnpm run build

      - name: Build Storybook
        working-directory: packages/design-system
        run: pnpm run build-storybook

      - name: Deploy Storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/design-system/storybook-static
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
